### PR TITLE
User/bill luu/sft 185 teams page base layout

### PR DESCRIPTION
**Pull request by bill-luu**
image
image

### CODE REVIEW

**Comment by bill-luu** [comment]
I used the native image aspect ratio of 3:2, how does this look?

image
image

**Comment by bill-luu** [comment]
This is 5:4
image
image

This is 1:1
image
image

**Comment by JaydenBischoff** [comment]
I like 5:4 too. Could you also add some space all around each white border so that each container is not touching?

**Comment by bill-luu** [comment]
image
image

**Comment by JaydenBischoff** [comment]
Can the space between the bottom of the text and border be made smaller? Otherwise it looks great!

**Comment by bill-luu** [comment]
image

**Pull request merged**
