### PR TITLE
ContactUs Page Complete without back-end implementation

### PR DESCRIPTION
**Pull request by JensVarughese**
The css styling can be subject to change. One example of this is the padding that was added to the top of the page to prevent overlapping. In addition, there is no back-end implementation for the message sender(Get In Touch). For now, the submit button will direct an email link with the contents of the message.

### CODE REVIEW

**Comment by JensVarughese** [comment]
I also forgot to mention that an api key with billing enabled has to be replaced witht he current api key.

**Comment by nathanaelhuh** [comment]
Why do we have to switch to a billing api? Is it due to being an organization or having more than 10 000 requests?

**Comment by nathanaelhuh** [comment]
Also I'm unsure if this happens on your PC but I think it's also something that needs to be fixed. I'm unsure if the new API key will fix this
Screen Shot 2020-03-28 at 10 25 52 AM

**Comment by nathanaelhuh** [comment]
Also, we're looking into changing the way we organize CSS but I think this is good for now

**Comment by JensVarughese** [comment]
That loading is because of the current api key. Its not loading properly because billing is not enabled

**Comment by nathanaelhuh** [comment]
I'm going to approve it now but I want Shamin and Jayden to also look it over before you squash and merge it

**Pull request merged**
