### PR TITLE
SFT-186 Create team member component

### PR DESCRIPTION
**Pull request by bill-luu**
Created a gallery-item component to dynamically display all members.

image
image

This PR is set to merge into SFT-187 for people viewing the diff, make sure this is put into master!

### CODE REVIEW

**Comment by bill-luu** [comment]
Ima be totally honest, I thought it was all red until you pointed it out

**Comment by bill-luu** [comment]
image

**Comment by JaydenBischoff** [comment]
I think that the outline of the active button would look better as the same red color.

**Comment by bill-luu** [comment]
Same red color:
image

darkgrey
image

black
image

**Comment by bill-luu** [comment]
Slightly darker red (#8f1414)
image

**Comment by bill-luu** [comment]
1.5 em
image

**Comment by bill-luu** [comment]
image
1.2em

**Comment by JaydenBischoff** [comment]
Can you make the numbers at the bottom go between the arrows and instead of having the numbers represent the number of members, can it be the number of pages?

**Comment by bill-luu** [comment]
errr not easily, at least not without switching away from [mat-paginator ](https://material.angular.io/components/paginator/overview) and maybe making our own component

**Comment by JaydenBischoff** [comment]
Okay that is fine then. We can just leave it like this.

**Pull request merged**
